export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CINEMA = 'GET_CINEMA';
export const GET_CINEMAS = 'GET_CINEMAS';
export const CINEMAS_LOADING = 'CINEMAS_LOADING';

export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE_TIMES_FOR_CINEMA = 'GET_MOVIE_TIMES_FOR_CINEMA';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_TIMES = 'GET_MOVIE_TIMES';
export const LOAD_MOVIE = 'LOAD_MOVIE';

export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIE_TIMES_LOADING = 'MOVIE_TIMES_LOADING';

export const GET_SEAT_TYPES = 'GET_SEAT_TYPES';
export const GET_SEAT_TYPE = 'GET_SEAT_TYPE';
export const SEAT_TYPE_LOADING = 'SEAT_TYPE_LOADING';
export const GET_SEAT_TYPE_FAIL = 'GET_SEAT_TYPE_FAIL';

export const GET_MOVIE_TIME = 'GET_MOVIE_TIME';
export const MOVIE_TIME_LOADING = 'MOVIE_TIME_LOADING';
export const GET_CINEMAS_WITH_HALLS = 'GET_CINEMAS_WITH_HALLS';
export const GET_MOVIES_FOR_MOVIE_TIMES = 'GET_MOVIES_FOR_MOVIE_TIMES';
export const GET_CINEMA_HALLS_FOR_MOVIE_TIMES = 'GET_CINEMA_HALLS_FOR_MOVIE_TIMES';
export const GET_CINEMAS_FOR_MOVIE_TIMES = 'GET_CINEMAS_FOR_MOVIE_TIMES';
export const GET_SEATS_TYPES_FOR_MOVIE_TIMES = 'GET_SEATS_TYPES_FOR_MOVIE_TIMES';

export const GET_CINEMA_HALLS = 'GET_CINEMA_HALLS';
export const GET_CINEMA_HALL = 'GET_CINEMA_HALL';
export const CINEMA_HALLS_LOADING = 'CINEMA_HALLS_LOADING';

export const GET_MOVIES_FROM_THE_MOVIE_DB = 'GET_MOVIES_FROM_THE_MOVIE_DB';
export const GET_MOVIES_FROM_THE_MOVIE_DB_FAIL = 'GET_MOVIES_FROM_THE_MOVIE_DB_FAIL';

export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_FAIL = 'GET_GENRES_FAIL';
export const CLEAN_MOVIES = 'CLEAN_MOVIES';

export const GET_BOOKED_SEATS = 'GET_BOOKED_SEATS';
export const BOOK_SEATS = 'BOOK_SEATS';
export const BOOK_SEATS_FAIL = 'BOOK_SEATS_FAIL';
export const CLEAN_SEATS_BOOKED_BY_USER = 'CLEAN_SEATS_BOOKED_BY_USER';

export const PREPARE_SEATS_FOR_BOOKING = 'PREPARE_SEATS_FOR_BOOKING';
export const REMOVE_SEATS_PREPARED_FOR_BOOKING = 'REMOVE_SEATS_PREPARED_FOR_BOOKING';

export const GET_GOODS = 'GET_GOODS';
export const PREPARE_GOODS = 'PREPARE_GOODS';
export const CLEAN_PREPARED_GOODS = 'CLEAN_PREPARED_GOODS';

export const INTENT_PAYMENT = 'INTENT_PAYMENT';
export const INTENT_PAYMENT_FAIL = 'INTENT_PAYMENT_FAIL';

